---
title: "access-models-outlets"
output: 
  github_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Aims

This document describes information specific to sharing data in public versus restricted outlets.

# Data sharing outlets

## Public

### Examples

- [Data Dryad](http://datadryad.org)
- [Dataverse](http://dataverse.org)
- [Figshare](http://figshare.org)
- [Open Science Framework (OSF)](http://osf.io)
- PI/Lab/university website
- Journal article supplemental material
- [OpenfMRI](http://openfmri.org)/[OpenNeuro](http://openneuro.org)

## Restricted outlets

- [Databrary](http://databrary.org)
    - Access granted only to authorized researchers at institutions that sign an [access agreement](https://www.databrary.org/access/policies/agreement.html) or individuals granted affiliate status by authorized researchers.
    - Data (including identifiable data items and video/audio recordings or photographs) are shared only with participant permission. Data are shared at one of [six release levels](https://www.databrary.org/access/guide/investigators/release/release-levels.html).
- [Inter-university Consortium on Political and Social Research (ICPSR)](https://www.icpsr.umich.edu/icpsrweb/)
- [Genographic Project](https://genographic.nationalgeographic.com/)
- [National Database for Autism Research (NDAR)](http://ndar.nimh.gov)
- [Neuroinformatics Tools & Resources Clearinghouse (NITRC)](https://www.nitrc.org/)