---
title: "sharing-consent-models"
date: "`r Sys.time()`"
output: 
  github_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Aims

This document describes the range of models used in seeking permission or consent from research participants to share data.

# Ways to secure permission to share

## Implicit permission to share data embedded in research consent

It is possible to state the conditions under which data will be shared in the research consent document, but not seek explicit permission to share via a participant's initials or signature.

### Example

> Your research records will be labeled with {*list all identifiers or data elements that apply*} {your code number, your date(s) of participation in the research,...} and will be stored {*describe safe area where research records are to be stored*} which may include electronic storage with a {University-approved} third party provider. 

> In addition, {selected parts of} your research records will be stored on {*describe site or sites where data will be shared*}. Access to the records will be granted {*describe who will have access*} for {*describe how long records will be stored or "indefinitely"*}. Information stored for use by others will include {*describe which records will be shared*}. {*If not sharing information with personal identifiers*} To the best of our knowledge, the data we release to {the general public or other investigators} will not contain information that can directly identify you. We will remove or change information that could easily identify you before files are shared [1]. {*If sharing information with identifiers, specify which ones.*} The shared information includes {video recordings, audio recordings, photographs, your birthdate, your Census block group (neighborhood)}. {*If sharing identifiable data in a restricted repository*} The information that could be used to identify you will only be shared with researchers who have been given specific permission to access the data and who have promised not to identify {or contact} you. The research records from this study might be used for other, future research projects. Those future projects can focus on any topic that might be unrelated to the goals of this study. Once research records have been shared with {other investigators or the general public}, they cannot be withdrawn or recalled.

> A security breach (break in or cyber attack) might lead to someone being able to link you to your data. This risk is very low because your data are stored in a secure database, and the information about your identity is stored separately from the other information and are linked only through a code.

### Pros

- Informs participants about the data that will be collected, how it will be stored and for how long.
- Reduces the record-keeping burden required if some participants give consent to share and some do not

### Cons

- Runs the risk that participants may balk at participating in research because of the, implied, requirement for data sharing.
- Impliesp that the risks (and benefits) of research participation are equivalent to those of data sharing.

## Explicit permission to share embedded in research consent

It is possible to include requests for approval or permission to share data within the language of the consent to participate in research.

### Pros

- Participants have one consent document to sign.
- Participants give explicit permission to share by initialling or signing near or below sharing language.
- Conditions of sharing (what data, with whom, stored/shared how, for how long, and for what purposes) can be described near and described similarly to descriptions of data storage provisions for the study itself.

### Cons

- Makes consent forms longer.
- May dissuade some participants from agreeing to participate in research.
- Risk of sharing may or may not be equivalent to that of participating in research.

## Seek separate permission to share **after** the research session or study has been completed.

### Pros

### Cons

## Seek permission to share retroactively (some time after the research has been concluded)

### Pros

### Cons

## Seek permission to share via a separate protocol that is devoted only to data sharing

# Resources

## Notes

[1]: https://www.icpsr.umich.edu/icpsrweb/content/datamanagement/confidentiality/conf-language.html
